### ISSUE TITLE
What about reading numbers?

### ISSUE THREAD

**Issue by v-python** [marcoconti83/read-ods-with-odfpy#12]
Your example works great for reading text, but there seems to be no example for reading numbers.  It would be nice if there was!

**Comment by marcoconti83** [comment]
Hi @v-python, have you tried reading a number with the example provided in the README? Which problems do you run into?

**Comment by v-python** [comment]
Thanks for the quick response.  Apologies.  It works fine.  I had some other code that didn't work, and when I looked at yours, it looked so similar, I couldn't imagine it worked either.  But it does.  And a more careful comparison of the code shows there are differences (you look at test:span AND text:a, the other code only at text:span), and you concatenate the content differently, using '{}{}'.format, the other code just does +=.  and so yours works, and the other doesn't.  I'm going to have to dig deeper to understand why.  Maybe c.data has different types for different values.
