### ISSUE TITLE
spreadsheet is a text object?

### ISSUE THREAD

**Issue by notweN-zinbieL** [marcoconti83/read-ods-with-odfpy#7]
I've been struggling with odfpy and every library that depends on it for a few hours.

line 35:
for sheet in self.doc.spreadsheet.getElementsByType(Table):
gives an error: 
AttributeError: 'Text' object has no attribute 'getElementsByType'

remove 'spreadsheet' seems to fix the problem.
new line 35:
for sheet in self.doc.getElementsByType(Table):

I don't know if this is just fixing the symptom but has solved all my current problems.

**Comment by marcoconti83** [comment]
Is this still relevant, @notweN-zinbieL ?

**Comment by notweN-zinbieL** [comment]
I don't know.  I eventually needed to write .ods files and started working directly with unzipped .xml files.

If nobody else suffered from this issue, let's close it.
