### ISSUE TITLE
Wrong object used in line 72

### ISSUE THREAD

**Issue by gohrner** [marcoconti83/read-ods-with-odfpy#9]
Lines 71/72 currently  read:
```
if (c.nodeType == 3):
     textContent = u'{}{}'.format(textContent, n.data)
```

However, I think they should read:
```
if (c.nodeType == 3):
    textContent = u'{}{}'.format(textContent, c.data)
```
Otherwise, ODSReader crashes immediately while trying to parse an ODS file with the Exception:

```
File "xxx/ODSReader.py", line 72, in readSheet
    textContent = u'{}{}'.format(textContent, n.data)
```

The parser works with the fix suggested above.

**Comment by marcoconti83** [comment]
Hi @gohrner , thanks for bringing up this issue. 
Would you feel comfortable opening a PR with your change in it?
